#!/bin/bash
d=`dirname $0`

ln -s $d/.bin ~/.bin
ln -s $d/.bashrc ~/.bashrc
ln -s $d/.vim ~/.vim
ln -s $d/.vimrc ~/.vimrc
ln -s $d/.gitconfig ~/.gitconfig
ln -s $d/.gitignore ~/.gitignore
ln -s $d/.git-completion.bash ~/.git-completion.bash
ln -s $d/.git-prompt.sh ~/.git-prompt.sh
ln -s $d/.jshintrc ~/.jshintrc
ln -s $d/.tmux.conf ~/.tmux.conf
ln -s $d/.xmonad ~/.xmonad

echo "Optionally link .bashrc: echo '. ~/.bashrc' >> ~/.bash_profile"
