#!/bin/bash
d=`dirname $0`

ln -s $d/.bin ~/.bin
ln -s $d/.bashrc ~/.bashrc
ln -s $d/.vim ~/.vim
ln -s $d/.vimrc ~/.vimrc
ln -s $d/git/gitconfig ~/.gitconfig
ln -s $d/git/gitignore ~/.gitignore
ln -s $d/.jshintrc ~/.jshintrc
ln -s $d/.tmux.conf ~/.tmux.conf

echo "Optionally link .bashrc: echo '. ~/.bashrc' >> ~/.bash_profile"
