require('packer').startup(function(use)
	use('wbthomason/packer.nvim')

	use('editorconfig/editorconfig-vim')
	use('tpope/vim-fugitive')
	use('tpope/vim-surround')
	use('tpope/vim-unimpaired')

	use(require('plugins/autopairs'))
	use(require('plugins/comment'))
	use(require('plugins/gitsigns'))
	use(require('plugins/lspconfig'))
	use(require('plugins/null_ls'))
	use(require('plugins/telescope'))
	use(require('plugins/tokyonight'))
	use(require('plugins/tree'))
	use(require('plugins/treesitter'))
	use(require('plugins/visual_multi'))
end)
